# I use Deno, not node
[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true

[[language]]
name = "elm"
language-servers = ["elm-language-server"]

[language-server.elm-language-server]
command = "elm-language-server"
#args = ["--stdio"]

[[language]]
name = "ruby"
# Solargraph needs these config options, but formatting still doesn't work. 
# See https://github.com/helix-editor/helix/issues/2623
# config = { solargraph = { diagnostics = true, formatting = true } }
indent = { tab-width = 4, unit = "    " }
# language-server = { command = "ruby-lsp" }
# Use rufo as formatter
formatter = { command = "rufo" , args = ["--simple-exit"]}
auto-format = true

[[language]]
name = "purescript"
scope = "source.purescript"
injection-regex = "purescript"
file-types = ["purs"]
roots = ["spago.dhall", "bower.json"]
comment-token = "--"
# language-server = { command = "purescript-language-server", args = ["--stdio"] }
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = { command = "purs-tidy", args = ["format"] }
grammar = "haskell"
