colors:
  body: none
  date: blue
  tags: cyan
  title: green
default_hour: 9
default_minute: 0
editor: vim
encrypt: false
highlight: true
indent_character: '|'
journals:
  '2019_20': /Users/brendantang/journal/2019-2020/journal.txt
  default:
    encrypt: true
    journal: /Users/brendantang/journal/journal.txt
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.8.3
